"""add electric fan settings

Revision ID: b7bd722bb4b5
Revises: 98c62f26e955
Create Date: 2026-08-12 06:04:12.992086

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b7bd722bb4b5'
down_revision: Union[str, None] = '98c62f26e955'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('electric_fan_settings',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('measurement_id', sa.BigInteger(), nullable=False),
    sa.Column('fan_speed', sa.SmallInteger(), nullable=False),
    sa.Column('power', sa.Text(), nullable=False),
    sa.Column('rhythm', sa.Text(), nullable=False),
    sa.Column('swing', sa.Text(), nullable=False),
    sa.Column('vertical_swing', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['measurement_id'], ['measurements.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('electric_fan_settings')
    # ### end Alembic commands ###
