pmv_threshold_settings:  # PMV閾値設定
  pmv_thresholds:  # PMVに基づくエアコンの設定閾値のリスト
    - threshold: -0.2  # PMVが-0.2以下の場合
      temperature: "29"       # 温度設定を29度にする
      mode: POWERFUL_HEATING  # モードを強力暖房に設定
    - threshold: -0.16  # PMVが-0.18以下の場合
      temperature: "25"       # 温度設定を25度にする
      mode: HEATING     # モードを暖房に設定
    - threshold: -0.1   # PMVが-0.13以下の場合
      temperature: "23"       # 温度設定を23度にする
      mode: HEATING     # モードを暖房に設定
    - threshold: 0      # PMVが0の場合
      temperature: "28"       # 温度設定を28度にする
      mode: FAN         # モードをファンに設定
      fan_speed: LOW    # ファンの速度を低に設定
    - threshold: 0.1    # PMVが0.1の場合
      temperature: "28"       # 温度設定を28度にする
      mode: FAN         # モードをファンに設定
      fan_speed: LOW    # ファンの速度を低に設定
    - threshold: 0.15   # PMVが0.15の場合
      temperature: "26"       # 温度設定を26度にする
      mode: COOLING     # モードを冷房に設定
    - threshold: 0.18   # PMVが0.18の場合
      temperature: "25"       # 温度設定を25度にする
      mode: COOLING     # モードを冷房に設定
    - threshold: 0.2    # PMVが0.2の場合
      temperature: "24"       # 温度設定を24度にする
      mode: COOLING     # モードを冷房に設定
    - threshold: 1      # PMVが1の場合
      temperature: "22"       # 温度設定を22度にする
      mode: POWERFUL_COOLING  # モードを強力冷房に設定

environmental_control_settings:  # 環境制御設定
  cooling_activation_criteria:  # 冷房を有効にするための基準
    outdoor_temperature_difference: 5  # 外気温との差（度）
    pmv_threshold: 0.5  # 冷房を有効にするためのPMV閾値
    temperature: "28"  # 停止時の送風温度（度）
    mode: FAN  # 停止時のモード
    fan_speed: LOW  # 停止時の風速
  heating_activation_criteria:  # 暖房を有効にするための基準
    outdoor_temperature_difference: 5  # 外気温との差（度）
    pmv_threshold: -0.3  # 暖房を有効にするためのPMV閾値
    temperature: "28"  # 停止時の送風温度（度）
    mode: FAN  # 停止時のモード
    fan_speed: LOW  # 停止時の風速
  dehumidification_settings:  # 露害設定
    temperature: "26"  # 露害温度（度）
    mode: DRY
    fan_speed: HIGH
  air_circulation_threshold: 2.0  # 空気循環のための部屋の温度差（度）
  dew_point_control:  # 露点温度に対する制御設定
    condensation_prevention_threshold: 1  # 結露防止のための余裕（度）
    pmv_threshold_for_cooling: 0.4  # 露点温度より低い場合でも、暑すぎる場合は冷房を有効にするためのPMV閾値
    cooling_stop_settings:  # 冷房停止時の設定
      temperature: "28"  # 停止時の送風温度（度）
      mode: FAN  # 停止時のモード
      fan_speed: HIGH  # 停止時の風速
    cooling_settings:  # 冷房時の設定
      temperature: "26"  # 冷房温度（度）
      mode: COOLING  # 冷房モード
      fan_speed: HIGH  # 冷房時の風速

weakest_aircon_settings:  # 最弱エアコン設定
  cooling_settings:  # 冷房時の設定
    temperature: "27"  # 温度（度）
    mode: COOLING  # モード
    fan_speed: LOW  # 風量
  heating_settings:  # 暖房時の設定
    temperature: "20"  # 温度（度）
    mode: HEATING  # モード
    fan_speed: LOW  # 風量
