# サーキュレーター設定
temperature_settings:
  high_speed_thresholds:  # 高温時のスピード設定
    - threshold: 3.0
      speed: 2
    - threshold: 2.5
      speed: 1
    - threshold: 2.0
      speed: 1
    - threshold: 1.5
      speed: 0
    - threshold: 1.0
      speed: 0

  normal_speed_thresholds:  # 高温以外の時のスピード設定
    - threshold: 3.0
      speed: 3
    - threshold: 2.5
      speed: 2
    - threshold: 2.0
      speed: 2
    - threshold: 1.5
      speed: 2
    - threshold: 1.0
      speed: 1
