high_temp_settings: # 高温時特有の設定
  met: # 代謝量に関する設定
    daytime: 1.0 # 日中の代謝量
    bedtime: 0.8 # 就寝時の代謝量
  icl: # 衣服熱抵抗に関する設定
    daytime: 0.6 # 日中の衣服熱抵抗
    bedtime: 0.8 # 就寝時の衣服熱抵抗
  time_settings: # 時間帯に関する設定
    lunch_time: # 昼食に関する時間設定
      start: "12:00" # 昼食開始時間（時）
      end: "13:00" # 昼食終了時間（時）
      met: 0.2 # 昼食時の加算代謝量
      use: true # 食事時間設定を使用するかどうかのフラグ
    dinner_time: # 夕食に関する時間設定
      start: "18:00" # 夕食開始時間（時）
      end: "20:00" # 夕食終了時間（時）
      met: 0.4 # 夕食の加算代謝量
      use: true # 夕食時間設定を使用するかどうかのフラグ
    pre_bedtime: # 就寝前に関する時間設定
      start: "23:00" # 就寝前開始時間（時）
      end: "0:00" # 就寝前終了時間（時）
      met: 0.3 # 就寝前の加算代謝量
      use: true # 就寝前時間設定を使用するかどうかのフラグ

low_temp_settings: # 低温時の設定
  met: # 代謝量に関する設定
    daytime: 1.0 # 日中の代謝量（活動中の推奨値）
    bedtime: 0.8 # 就寝時の代謝量（安静時の推奨値）
  icl: # 衣服熱抵抗に関する設定
    daytime: 1.0 # 日中の衣服熱抵抗（軽い服装での推奨値）
    bedtime: 2.0 # 就寝時の衣服熱抵抗（暖かい服装での推奨値）
  time_settings: # 時間帯に関連する設定
    heating: # 暖房使用時の電気代に応じた調整設定
      use: true # 暖房の時間設定を適用するかどうか
      high_cost: # 電気代が高い時間帯の設定
        start: "07:40" # 高い電気代が適用される開始時間
        end: "11:00" # 高い電気代が適用される終了時間
        adjustment: 0.2 # 電気代が高い時間帯での衣服熱抵抗の増加量
      low_cost: # 電気代が低い時間帯の設定
        start: "17:00" # 低い電気代が適用される開始時間
        end: "18:00" # 低い電気代が適用される終了時間
        adjustment: 0.2 # 電気代が低い時間帯での衣服熱抵抗の増加量
