# 熱特性に関する設定
thermal_properties:
  wall_thermal_conductivity: 0.5  # 壁の熱伝導率 [W/(m K)]
  ceiling_thermal_conductivity: 0.15  # 天井の熱伝導率 [W/(m K)]
  floor_thermal_conductivity: 0.26  # 床の熱伝導率 [W/(m K)]
  window_thermal_conductivity: 2.1  # 窓の熱伝導率 [W/(m K)]
  window_to_wall_ratio: 0.3  # 窓の面積の壁に対する比率
  wall_surface_heat_transfer_resistance: 0.11  # 壁の表面熱伝達抵抗 [(m K)/W]
  ceiling_surface_heat_transfer_resistance: 0.09  # 天井の表面熱伝達抵抗 [(m K)/W]
  floor_surface_heat_transfer_resistance: 0.15  # 床の表面熱伝達抵抗 [(m K)/W]
  temp_diff_coefficient_under_floor: 0.7  # 床下の温度差係数

# 屋根の表面温度に関する設定
roof_surface_temperatures:
  over_25: 40  # 外気温が25度以上の時の屋根表面温度
  over_30: 50  # 外気温が30度以上の時の屋根表面温度
  over_35: 70  # 外気温が35度以上の時の屋根表面温度
  over_40: 80  # 外気温が40度以上の時の屋根表面温度

# 西側外壁の表面温度に関する設定
wall_surface_temperatures:
  over_25: 30  # 外気温が25度以上の時の西側外壁表面温度
  over_30: 35  # 外気温が30度以上の時の西側外壁表面温度
  over_35: 40  # 外気温が35度以上の時の西側外壁表面温度
  over_40: 50  # 外気温が40度以上の時の西側外壁表面温度
