name: run_script
on:
  push:
  workflow_dispatch:
  schedule:
    - cron: "*/10 * * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        id: setup-python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      # Pythonバージョンのキャッシュ
      - name: "Cache: Cache Python"
        id: python-cache
        uses: actions/cache@v4
        with:
          path: ${{ env.pythonLocation }}
          key: ${{ runner.os }}-python-${{ steps.setup-python.outputs.python-version }}-${{ hashFiles('requirements.txt') }}

      # pipキャッシュを取得または保存する
      - name: "Shell: Get pip cache dir"
        id: pip-cache-dir
        if: steps.python-cache.outputs.cache-hit != 'true'
        run: |
          python -m pip install -U pip
          pip install -U wheel
          echo "pip-cache-dir=$(pip cache dir)" >> $GITHUB_ENV

      - name: "Cache: Cache pip"
        if: steps.python-cache.outputs.cache-hit != 'true'
        uses: actions/cache@v4
        with:
          path: ${{ env.pip-cache-dir }}
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      # 依存関係のインストール（キャッシュがない場合）
      - name: Install dependencies
        if: steps.python-cache.outputs.cache-hit != 'true'
        run: pip install -r requirements.txt

      - name: Run script
        env:
          SWITCHBOT_ACCESS_TOKEN: ${{ secrets.SWITCHBOT_ACCESS_TOKEN }}
          SWITCHBOT_SECRET: ${{ secrets.SWITCHBOT_SECRET }}
          SWITCHBOT_CIRCULATOR_DEVICE_ID: ${{ secrets.SWITCHBOT_CIRCULATOR_DEVICE_ID }}
          SWITCHBOT_CEILING_DEVICE_ID: ${{ secrets.SWITCHBOT_CEILING_DEVICE_ID }}
          SWITCHBOT_FLOOR_DEVICE_ID: ${{ secrets.SWITCHBOT_FLOOR_DEVICE_ID }}
          SWITCHBOT_STUDY_DEVICE_ID: ${{ secrets.SWITCHBOT_STUDY_DEVICE_ID }}
          SWITCHBOT_OUTDOOR_DEVICE_ID: ${{ secrets.SWITCHBOT_OUTDOOR_DEVICE_ID }}
          SWITCHBOT_BEDROOM_DEVICE_ID: ${{ secrets.SWITCHBOT_BEDROOM_DEVICE_ID }}
          SWITCHBOT_AIR_CONDITIONER_DEVICE_ID: ${{ secrets.SWITCHBOT_AIR_CONDITIONER_DEVICE_ID }}
          SWITCHBOT_AIR_CONDITIONER_SUPPORT_DEVICE_ID: ${{ secrets.SWITCHBOT_AIR_CONDITIONER_SUPPORT_DEVICE_ID }}
          SWITCHBOT_BASE_URL: ${{ secrets.SWITCHBOT_BASE_URL }}
          SUPABASE_PROJECT_URL: ${{ secrets.SUPABASE_PROJECT_URL }}
          SUPABASE_API_KEY: ${{ secrets.SUPABASE_API_KEY }}
          JMA_AREA_NAME: ${{ secrets.JMA_AREA_NAME }}
          JMA_AREA_CODE: ${{ secrets.JMA_AREA_CODE }}
          LINE_NOTIFY_ACCESS_TOKEN: ${{ secrets.LINE_NOTIFY_ACCESS_TOKEN }}
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: |
          python main.py
